/* Copyright 2008-2011 The MathWorks, Inc. */
/* Generated by genpubheader from export/include/SimulinkBlock/sl_core_block_spec.hpp. */

#ifndef SL_CORE_BLOCK_SPEC_HPP
#define SL_CORE_BLOCK_SPEC_HPP

#ifdef SUPPORTS_PRAGMA_ONCE
#pragma once
#endif

#ifdef BUILDING_SIMULINKBLOCK

# define SL_CORE_BLOCK_EXPORT_CLASS    DLL_EXPORT_SYM
# define SL_CORE_BLOCK_EXPORT_FCN      DLL_EXPORT_SYM
# define SL_CORE_BLOCK_EXPORT          DLL_EXPORT_SYM
# define SL_CORE_BLOCK_EXPORT_EXTERN_C extern "C" DLL_EXPORT_SYM

#elif defined(DLL_IMPORT_SYM)

# define SL_CORE_BLOCK_EXPORT_CLASS    DLL_IMPORT_SYM
# define SL_CORE_BLOCK_EXPORT_FCN      DLL_IMPORT_SYM
# define SL_CORE_BLOCK_EXPORT          DLL_IMPORT_SYM
# define SL_CORE_BLOCK_EXPORT_EXTERN_C extern "C" DLL_IMPORT_SYM

#else

#ifdef __cplusplus
#define SL_CORE_BLOCK_EXPORT_EXTERN_C extern "C"
#else
#define SL_CORE_BLOCK_EXPORT_EXTERN_C extern
#endif

# define SL_CORE_BLOCK_EXPORT_CLASS  extern
# define SL_CORE_BLOCK_EXPORT_FCN    extern
# define SL_CORE_BLOCK_EXPORT        extern

#endif

#endif 

